# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-executables-have-shebangs
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 1.11.0
  hooks:
    - id: script-must-have-extension
      name: Local policy is to use .sh or .bash extension for libraries.
      types: [shell, non-executable]
    - id: script-must-not-have-extension
      name: Local policy is not to use extension for executable scripts.
      types: [shell, executable]
- repo: local
  hooks:
    - id: check-makefile
      name: Check Makefile
      description: Check if the Makefile is correctly formatted
      language: script
      types: ["makefile"]
      entry: ./.hooks/check-makefile.sh
