- hosts: localhost
  connection: local
  tasks:
    - name: Check supported operating system
      ansible.builtin.assert:
        that:
          - ansible_facts['system'] == 'Darwin' or ansible_facts['distribution'] in ['Ubuntu', 'Archlinux']
        fail_msg: Provisioning supports macOS, Ubuntu, and Arch Linux.
      tags: always

    - ansible.builtin.import_tasks: ./tasks/packages.yml
    - ansible.builtin.import_tasks: ./tasks/bash.yml
    - ansible.builtin.import_tasks: ./tasks/pip.yml
    - ansible.builtin.import_tasks: ./tasks/rust.yml
    - ansible.builtin.import_tasks: ./tasks/git-lfs.yml
