- hosts: localhost
  become: true
#  pre_tasks:
#    - name: Updating repositories
#      apt: update_cache=yes
#      changed_when: False
  tasks:
    - include: ./tasks/repositories.yml
    - include: ./tasks/packages.yml
    - include: ./tasks/bash.yml
    - include: ./tasks/vim.yml
    - include: ./tasks/pathogen.yml
    - include: ./tasks/pip.yml
    - include: ./tasks/gem.yml
    - include: ./tasks/rust.yml
    - include: ./tasks/syncthing.yml
    - include: ./tasks/virtualization.yml
    - include: ./tasks/virtualbox.yml
    - include: ./tasks/git-lfs.yml
