- name: Checking if osync is already installed
  shell: command osync.sh >/dev/null 2>&1
  register: osync_installed
  check_mode: no
  ignore_errors: yes
  failed_when: false
  tags: osync

- name: osync is already installed
  debug:
    var: osync_installed
  when: osync_installed.rc == 0 or osync_installed.rc == 128
  check_mode: no
  tags: osync

- name: osync is not installed
  debug:
    var: osync_installed
  when: osync_installed.rc != 0 and osync_installed.rc != 128
  tags: osync

- name: Cloning osync repository
  git:
    repo: https://github.com/deajan/osync
    dest: /tmp/osync
    version: stable
  register: osync_git
  when: osync_installed.rc != 0 and osync_installed.rc != 128
  tags: osync

- name: Installing osync
  shell: ./install.sh chdir=/tmp/osync
  tags: osync
  when: osync_git.skipped is not defined and osync_git.failed == false

- name: Removing osync temp files
  file:
    state: absent
    path: /tmp/osync
  tags: osync
  when: osync_git.skipped is not defined and osync_git.failed == false
