- name: Installing packages
  package: name={{item}}
  with_items:
    - vim
    - git
    - inotify-tools
    - stow
    # Gnome color picker
    - gpick
    # A simple PDF viewer
    - zathura
    # Terminal file manager
    - ranger
    # This is used by ranger to highlight code inside the preview
    - highlight
    # A new vim
    - neovim 
    # EDA electronic design automation software
    - kicad
    # Dependencies for YouCompleteMe
    # - build-essential
    - cmake
    # - python-dev
    # - python3-dev
    # A simple image viewer
    - feh
    - gimp
    - neofetch
    - jq
    - unzip
    # with i3
    - compton
    # manage your tasks
    - taskwarrior

- name: Installing arch packages
  package: name={{item}}
  with_items:
    - python3
    - python2
    - python2-pip
    - python-pip
    - base-devel
    # with i3
    - compton
    # manage your task
    - task
    # keeps track of how much time each task takes
    - timew
  when: ansible_distribution == 'Archlinux'

- name: Installing ubuntu or debian packages
  package: name={{item}}
  with_items:
    - build-essential
    - python-dev
    - python3-dev
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
