- name: Install packages
  apt: name={{item}}
  with_items:
    - vim
    - git
    - inotify-tools
    - stow
    # Gnome color picker
    - gpick
    # A simple PDF viewer
    - zathura
    # Terminal file manager
    - ranger
    # This is used by ranger to highlight code inside the preview
    - highlight
    # A new vim
    - neovim 
    # EDA electronic design automation software
    - kicad
