- name: Creating directories for pathogen installation
  file: path={{item}} state=directory
  with_items:
    - "~/.vim/autoload"
    - "~/.vim/bundle"
  become: no
  tags: pathogen

- name: Downloading and installing pathogen
  get_url:
    url: https://tpo.pe/pathogen.vim
    dest: ~/.vim/autoload/pathogen.vim
  become: no
  tags: pathogen
