- name: Installing pip packages
  pip:
    name: "{{ item }}"
  with_items:
    - flake8
    - cheat
    # render markdown file
    - grip
    # pipenv environment switcher
    - pipenv-pipes
    # useful commands to works with virtualenv
    - virtualenvwrapper
  tags: pip
