# This entity represent an autofs configuration file
autofs_configuration:
  - filename: auto.nfs
    mounts:
      # for more information on valid nfs options see nfs(5)
      - key: example
        options: "-fstype=nfs"
        location: "//192.168.1.1/server"
  - filename: auto.server1
    mounts:
      - key: example
        options: "-fstype=nfs"
        location: "//192.168.1.1/server"
