# This entity represent an autofs configuration file
autofs_configuration:
  - filename: auto.nfs
    mounts: 
      - key: example
        options: "-fstype=nfs"
        location: "//192.168.1.1/server"
  - filename: auto.nfs
    mounts: 
      - key: example
        options: "-fstype=nfs"
        location: "//192.168.1.1/server"
