#!/usr/bin/env sh


is_integer() {
	if [ "$#" -ne 1 ]; then
		echo "Wrong number of arguments for function is_integer" >&2
		exit -1
	fi

	case "$1" in
		''|*[!0-9]*)
		echo "$1 is not a valid integer value." >&2
		exit -1
		;;
	esac
}

if [ "$#" -ne 3 ]; then
	echo "Wrong number of arguments." >&2
	exit -1
fi

filepath="$1"

start_line_no=$2
end_line_no=$3

is_integer "$start_line_no"
is_integer "$end_line_no"

sed -n "${start_line_no},${end_line_no}p" "$filepath" | boxes
commented_text="$(sed -n "${start_line_no},${end_line_no}p" "$filepath" | boxes)"

printf '%s\n' "$commented_text" | gsed -i "${start_line_no},${end_line_no}{r /dev/stdin
d}" "$filepath"
