#!/usr/bin/env bash

filepath="$1"

start_line_no=$2
end_line_no=$3

sed -n "${start_line_no},${end_line_no}p" "$filepath" | boxes
commented_text="$(sed -n "${start_line_no},${end_line_no}p" "$filepath" | boxes)"

gsed -i "${start_line_no},${end_line_no}{r /dev/stdin
d}" "$filepath" <<< "$commented_text"
