#!/usr/bin/env bash
#
# @author 		Fabrizio Destro
# @copyright	Copyright 2018, Fabrizio Destro
# @license
#  This work is licensed under the terms of the MIT license.
#  For a copy, see <https://opensource.org/licenses/MIT>.

if [ ! -d ~/.dotfiles/scripts ]; then
	echo "Missing dotfiles directory."
	exit
fi

{
	cd ~/.dotfiles/scripts
	find ./ -type f -print0 | while IFS= read -r -d $'\0' line; do
		filename=$(basename "$line")

		[[ ! -x "$filename" ]] && chmod +x "$filename"

		(
			cd .scripts \
				&& [ ! -f "${filename%.*}" ] \
				&& ln -s ../$filename ${filename%.*}
		)
	done
}
