#!/usr/bin/env bash
#
# @author 		Fabrizio Destro
# @copyright	Copyright 2018, Fabrizio Destro
# @license
#  This work is licensed under the terms of the MIT license.
#  For a copy, see <https://opensource.org/licenses/MIT>.


usage() {
	cat << EOU
license

Usage:
	license list
	license description <license>
	license <license>
EOU
}


if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
	usage
	exit 0
fi

if [ "$#" -eq 1 ] && [ "$1" = "list" ]; then
	curl -s https://api.github.com/licenses | jq -r ".[] | [.key, .name] | @csv"
elif [ "$#" -eq 2 ] && [ "$1" = "description" ]; then
	license=$2
	curl -s "https://api.github.com/licenses/$license" | jq -r ".description"
elif [ "$#" -eq 1 ]; then
	license=$1
	# TODO with some licenses you have to modify the body, see mit.
	body=$(curl -s "https://api.github.com/licenses/$license" | jq -r '.body')
	echo "$body"
else
	usage >&2
	exit 2
fi
