#!/usr/bin/env sh
#
# ANSI color scheme script featuring Space Invaders
#
# Original: http://crunchbanglinux.org/forums/post/126921/#p126921
# Modified by lolilolicon
#
# Fixed by dexpota: there was an issue where the aliens didn't align, fixed
# with some spaces
#

f=3 b=4
i=0
while [ "$i" -le 7 ]; do
  eval "f$i=\$(printf '\033[3%sm' \"$i\")"
  eval "b$i=\$(printf '\033[4%sm' \"$i\")"
  i=$((i + 1))
done
bld=$(printf '\033[1m')
rst=$(printf '\033[0m')

cat << EOF

 $f1   ▀▄   ▄▀     $f2  ▄▄▄████▄▄▄    $f3   ▄██▄     $f4   ▀▄   ▄▀     $f5  ▄▄▄████▄▄▄    $f6   ▄██▄  $rst
 $f1  ▄█▀███▀█▄    $f2 ███▀▀██▀▀███   $f3 ▄█▀██▀█▄   $f4  ▄█▀███▀█▄    $f5 ███▀▀██▀▀███   $f6 ▄█▀██▀█▄$rst
 $f1 █▀███████▀█   $f2 ▀▀███▀▀███▀▀   $f3 ▀█▀██▀█▀   $f4 █▀███████▀█   $f5 ▀▀███▀▀███▀▀   $f6 ▀█▀██▀█▀$rst
 $f1 ▀ ▀▄▄ ▄▄▀ ▀   $f2  ▀█▄ ▀▀ ▄█▀    $f3 ▀▄    ▄▀   $f4 ▀ ▀▄▄ ▄▄▀ ▀   $f5  ▀█▄ ▀▀ ▄█▀    $f6 ▀▄    ▄▀$rst

 $bld$f1 ▄ ▀▄   ▄▀ ▄   $f2  ▄▄▄████▄▄▄    $f3   ▄██▄     $f4 ▄ ▀▄   ▄▀ ▄   $f5  ▄▄▄████▄▄▄    $f6   ▄██▄  $rst
 $bld$f1 █▄█▀███▀█▄█   $f2 ███▀▀██▀▀███   $f3 ▄█▀██▀█▄   $f4 █▄█▀███▀█▄█   $f5 ███▀▀██▀▀███   $f6 ▄█▀██▀█▄$rst
 $bld$f1 ▀█████████▀   $f2 ▀▀▀██▀▀██▀▀▀   $f3 ▀▀█▀▀█▀▀   $f4 ▀█████████▀   $f5 ▀▀▀██▀▀██▀▀▀   $f6 ▀▀█▀▀█▀▀$rst
 $bld$f1  ▄▀     ▀▄    $f2 ▄▄▀▀ ▀▀ ▀▀▄▄   $f3 ▄▀▄▀▀▄▀▄   $f4  ▄▀     ▀▄    $f5 ▄▄▀▀ ▀▀ ▀▀▄▄   $f6 ▄▀▄▀▀▄▀▄$rst


                                     $f7 ▌$rst

                                   $f7 ▌$rst

                              $f7     ▄█▄    $rst
                              $f7 ▄█████████▄$rst
                              $f7 ▀▀▀▀▀▀▀▀▀▀▀$rst

EOF
