#!/usr/bin/env bash
#
# @author 		Fabrizio Destro
# @copyright	Copyright 2018, Fabrizio Destro
# @license
#  This work is licensed under the terms of the MIT license.
#  For a copy, see <https://opensource.org/licenses/MIT>.

# TODO make this script hunts more tags

usage() {
	cat << EOU
tags-hunt

Usage:
	tags-hunt <directory> [options]

Options:
	-t,--todo  Search for TODO tags.
	-b,--bug  Search for BUG tags.
	-f,--fix-me  Search for FIXME tags.
	-h,--hack  Search for HACK tags.
	-u,--undone  Search for UNDONE tags.
	-v,--verbose  Output more informations.
	-d,--debug  Enable debug mode, output even more informations.
EOU
}


verbose() {
	[ $verbose = "true" ]
}

search() {
	local tag="$1"
	local result=$(grep -n "$tag" "$filename")

	if [ ! -z "$result" ]; then
		printf "%s\n" "$filename"
		#printf "\t%.10s\n" "$result"
		echo "$result" |  sed "s/^\(.\{0,${columns}\}\).*$/  \1/"
	fi
}

main() {
	columns=$(tput cols)
	columns=$(expr $columns - 4)

	find $directory \( -type d -name '*.[!.]*' \) -prune \
		-or -type f -not -name '.*' -print0 | while read -d $'\0' filename
	do
		search TODO
	done
}

todo=false
bug=false
fix_me=false
hack=false
undone=false
verbose=false
debug=false
directory=""

for argument in "$@"; do
	case "$argument" in
		-t|--todo) todo=true ;;
		-b|--bug) bug=true ;;
		-f|--fix-me) fix_me=true ;;
		-h|--hack) hack=true ;;
		-u|--undone) undone=true ;;
		-v|--verbose) verbose=true ;;
		-d|--debug) debug=true ;;
		--help)
			usage
			exit 0
			;;
		-*)
			echo "Unknown option: $argument" >&2
			usage >&2
			exit 2
			;;
		*)
			if [ -n "$directory" ]; then
				usage >&2
				exit 2
			fi
			directory=$argument
			;;
	esac
done

if [ -z "$directory" ]; then
	usage >&2
	exit 2
fi

main
